import type { Metadata } from "next";
import "./ui/styles/globals.css";
import { ReactNode } from "react";
import { inter } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
